--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MuhammadRestu999/LoginForm
build-by-default: true
branches:
- main
projects:
  LoginForm:
    path: ""
    icon: "icom.png" # https://www.flaticon.com/free-icons/login
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^2.1.0
...
